print("##############################")
print("#                            #")
print("#   Rayfha Zafira Az-zahra   #")
print("#        2210817220022       #")
print("#                            #")
print("##############################")